### ISSUE TITLE
CGI Disks tab

### ISSUE THREAD

**Issue by dragon2611** [moosefs/moosefs#277]
Either a bug in the Cgi interface or something in my install it doesn't like.

CGI version: 3.0.105 ; python: 2.7

```
Traceback (most recent call last):   File "/usr/share/mfscgi/mfs.cgi", line 4458, in      conn = MFSConn(hostip,port)   File "/usr/share/mfscgi/mfs.cgi", line 1362, in __init__     self.connect()   File "/usr/share/mfscgi/mfs.cgi", line 1385, in connect     self.socket.connect((self.host,self.port))   File "/usr/lib/python2.7/socket.py", line 228, in meth     return getattr(self._sock,name)(*args) timeout: timed out
--
```

**Comment by jkiebzak** [comment]
"timeout: timed out".... firewall setting on the master?

**Comment by dragon2611** [comment]
Shouldn't be, the CGI interface is running on the master itself and both the loopback and internal interfaces are currently allowing everything.

**Comment by dragon2611** [comment]
Ahh right the problem occurs if you have a chunkserver that's got high latency to the master, I have one that's ~130ms away. 

It seems MFS can mostly work with the latency other than it breaking a few things in the CGI interface (the chunkserver load graphs also hang for quite a while).

Obviously any file accesses that hit that chunkserver are somewhat slow, but that's expected with the RTT time being what it is.

**Comment by dragon2611** [comment]
I think the best solution here is to take out that chunkserver, it was an interesting experiment but it needs to be either removed or connected to a master a bit closer to it.
