### ISSUE TITLE
chunkserver: inefficient handling of duplicate chunks

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#327]
I moved an HDD from one chunkserver to another (same label) so some duplicate chunks ended up on one chunkserver. That exposed several problems:

  * scanning is incredibly slow -- around dozen chunks per second so full scan takes 20+ hours.

  * during scanning all other HDDs on the same chunkserver exhibited numerous `wrong header` errors.

  * scanning blocked I/O everywhere so all the cluster was frozen for the duration of very slow scan -- that includes unrelated storage classes placed to chunkservers with different labels. Under no circumstances scanning should block I/O in unrelated data that is placed elsewhere.

  * in the aftermath some chinks were lost/missing (`INVALID COPIES`).

  * unlike LizardFS that removes duplicate chunks during scanning, MooseFS holds them to be deleted later. Too bad if you need to restart chunkserver before scheduled deletion as slow scanning and all the above problems will happen again.

Interesting to note that LizardFS have none of those problems.

**Comment by chogata** [comment]
One important question before we go any further: what is the version of the chunk server you've pulled your hdd from and what is the version of the chunk server you've moved it to?

**Comment by onlyjob** [comment]
Both latest release 3.0.109 of course.

**Comment by chogata** [comment]
Okay, so we have several separate issues here:

1) _Scanning is slow_ - scanning with duplicates is always slower. It can be slowed down even more if for some reason (i.e. chunks available only on this one chunk server) the chunk sever gets a lot of i/o requests to its chunks while still scanning. Nevertheless, the speed you give here (~dozen chunks per second) is suspiciously slow, it should not be that slow. But see 2)

2) `wrong header` - this is strange, because unless you connected a disk from a newer chunk server to an older one OR your disk is not working correctly (did you fsck all the disks in this chunk server? ) and has corrupted data, this should never happen. Can you paste an excerpt from your chunk server's log, containing a few of those `wrong header` lines and all the other lines in between?

3) Slow scanning of one chunk server blocking I/O for the whole MooseFS instance - this is something we tested and could not repeat. We even modified chunk server code and added some `sleep` calls to the scanning code, and run this modified chunk server together with regular chunk servers and we could still use our instance of MooseFS normally.

4) Lost/missing chunks - we come back to problem 2) - should not happen, unless there is a corrupted disk somewhere.

5) This is on purpose, because of data errors. If we find a duplicate during scanning and we delete one copy immediately and shortly after the other copy turns out to be corrupted - we are missing a copy. This means replication, over network (or a lost chunk if this was the last valid copy in the system). If we don't delete it, we still have it, the corrupted copy is deleted instead. 
There are many cases where MooseFS is not "hasty" in deleting redundant chunks and in some cases that helped MooseFS users recover data that would otherwise be lost. "Better safe than sorry" is kinda our motto :)
Nevertheless, if you can provide us with a valid use case (other than restarting a chunk server hourly just because) we could make the length of time those duplicates are kept a configurable option.

**Comment by onlyjob** [comment]
2:
HDD is fine, no physical or structural errors whatsoever. I've fsck'd the ext4 file system.
```
chunk_readcrc: file:/mnt/02/ext4//AB/chunk_000000000348EF1C_00000001.mfs - wrong header
hdd_io_begin: file:/mnt/02/ext4//AB/chunk_000000000348EF1C_00000001.mfs - read error: Success (errno=0)
```

3:
What do you think might be causing this worst side effect of slow scanning?

5:
It is not the delay as such which is not working properly anyway:

```
Jan 21 01:17:36: on drive '/mnt/03/ext4/' 5653820 chunk duplicates detected - will remove them in 1 hours
...
Jan 21 10:17:45: on drive '/mnt/03/ext4/' 5653820 chunk duplicates detected - will remove them in 10 hours
...
Jan 22 02:18:01: on drive '/mnt/03/ext4/' 5653820 chunk duplicates detected - will remove them in 26 hours
```

Chunkserver is just adding more and more hours without deleting duplicates...

**Comment by onlyjob** [comment]
Just to reaffirm that side effect 3 is perfectly reproducible for me. Just today I've rebooted machine with archival chunkserver which storage class have some undergoal chunks. Chunkserver have around 20 million chunks so scanning is not very fast. After reboot I'm logging into Desktop Environment (user's home folder is on MooseFS) and DE freezes for 15...20 minutes until the very second when chunkserver finished scanning. As per definition of storage classes, scanning chunkserver holds no chunks from the home folder...

**Comment by chogata** [comment]
As for 5 - this is a bug in reporting. The time is 168 hours (1 week), but because of a bug it's reported backwards (it should say how much time is left, but it says how much time has passed instead). So in your case, it will grow up to 168, then you will no longer see this message, because the duplicates will be deleted.
We fixed the reporting for the next release.

We are investigating the rest. Could you please hexdump the first 20 bytes of this chunk: `/mnt/02/ext4//AB/chunk_000000000348EF1C_00000001.mf`? We are trying to find a scenario in which the `wrong header` message is not connected with chunk corruption, but so far, we can't.

**Comment by onlyjob** [comment]
Thanks.

```
# hexdump -C -n 20 /mnt/02/ext4/AB/chunk_000000000348EF1C_00000001.mfs
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000014
```

**Comment by chogata** [comment]
Well, this most definitely is not a correct chunk header. So it's not a bug in the chunk server's behaviour, it's the real corruption of chunks. The question is, why are your chunks corrupted.

We don't see an easy answer - there is no code in MooseFS that writes zero bytes into the beginning of a chunk. So either it's a corruption caused by something not related to MooseFS (OS failure, controller failure etc.) or some very unlikely and convoluted scenario in MooseFS. We will try to run more tests (moving disks between chunk servers), but at this point in time we are leaning toward external corruption as the answer.

With corrupted chunk headers (and possibly content too, then) the lost chunk problem is self-explanatory.

As for the I/O blocking - our test did include a slow scanning chunk server, but it did not include corrupted chunks. We will add that factor and see if the freezing of whole system will occur.

**Comment by onlyjob** [comment]
Interesting question is why corrupted headers manifested from the moment since HDD was moved.
First I've investigated possibility of hardware problem and found nothing. Time correlation suggests that the problem have something to do with MooseFS. Also MooseFS is an exclusive user of the HDD's file system. Also I've moved another HDD between chukservers and the issue with wrong headers manifested there as well, also from the moment when a HDD from another chunkserver was introduced. Basically I had 3 archival chunkservers and I've consolidated them into 2 by accommodating HDDs of the decommissioned chunkserver into two remaining ones.

Of course you know better but I doubt that precence of corrupted chunks is blocking I/O. More likely it have something to do with on-going replication...  Undergoal chunks are due to the fact that one HDD is now disabled as it took 24+ hours to scan it up to 50% and all this time cluster was unusable. I had to comment HDD in the `mfshdd.cfg` as we could not tolerate further down time...

**Comment by onlyjob** [comment]
I'd like to add more info (comment) on "wrong header" situation. Two chunkservers started to exhibit multiple "wrong header" errors on all local disks from the moment they received a new HDD from a third (decommissioned) chunkserver. I've thoroughly investigated possibility of hardware errors and found none. One chunkserver have ECC RAM and 6 local HDDs that all reported multiple "wrong header" errors in the complete absence of any errors in logs (hardware-related or otherwise). `fsck` had no errors to fix and errors continue to be logged. That looks like a software bug to me rather than a hardware malfunction.

**Comment by chogata** [comment]
Thank you for all the info. We are running tests right now, we will let you know as soon as we find something.

**Comment by chogata** [comment]
We tried to simulate your situation. We created a bunch of files with goal set so they would only be recorded on 2 selected chunk servers. We then moved one disk from first chunk server to the other. We had duplicates, but no wrong headers, I/O of the rest of the cluster was not affected. We tried this first leaving the `.chunkdb` untouched on the disk we moved, second time with deleting `.chunkdb`. We still cannot replicate your bug.

Can you give us any more hints? You wrote that you inserted disks from one, specific, decommissioned chunk server. While this decommissioned chunk server was still active, was it in an active installation (that got a lot requests to read those chunks)? Was it a fresh install of 3.0.109 or was it upgraded? If it was upgraded, do you remember from which version?

Also, do you have any more disks taken out of this decommissioned chunk server that you did not put into another chunk server yet? If yes, can you dump headers from a few random chunk files (without connecting the disk to a chunk server, of course)? First 8 bytes will be enough.

**Comment by onlyjob** [comment]
Decommissioned (healthy) chunkserver was upgraded 3.0.104 --> 3.0.105 (--> 3.0.107 maybe) --> 3.0.109. Last upgrade was some days before decommissioning. Chunkserver was stopped once its HDDs were absorbed and manually removed from CGI. While it was operational there were no errors logged... I've hexdump'ed random file and predictably there is a content:

```
# hexdump -C -n 00/20 chunk_00000000008521B8_00000001.mfs
00000000  4d 46 53 43 20 31 2e 30  00 00 00 00 00 85 21 b8  |MFSC 1.0......!.|
00000010  00 00 00 01                                       |....|
00000014
```

**Comment by chogata** [comment]
We've run more tests, we upped the number of files, we tried to exhaust the 2 chunk servers involved in disk switching with I/O operations. Basically, we tried to do all the "bad" things we could think of when moving a disk from one chunk server to another. Still no errors, our chunks are not corrupted, neither on the disk that was moved nor on other disks.

I'm very sorry, but we cannot do anything with a bug we are unable to replicate.

We can try to run more tests, but for that to make any sense, we need detailed information about your cluster:
- hardware details and os details of the machine with master and machines with chunk servers
- cluster configuration (at the moment of putting the "old-new" disk in): how many chunk servers, how many disks in each one, approximately how many mounts connected and performing I/O - best estimate
- fs on the disks that held chunks in the chunk server that had wrong headers, both the old ones and the "old-new" one
- all your configuration files for MooseFS (either full files or all the settings you've changed from default)
- all non-typical configuration of your os regarding performance - hard to say what you might have set, so whatever you can think of related with ram use, fs caching etc.
- if possible, full upgrade history of affected chunk servers (the acitve ones, not the decomissioned one) and the master server

Now, some side notes from the tests:
At one point, we connected a disk with over 2 million chunks to a chunk server, with > 90% duplicates. Scanning (without .chunkdb, so full scan) took 222 seconds, that is ~9400 chunks per second. During the scanning process there were 4 active mount processes that wrote, appended, deleted and wrote files that had at least one chunk (and sometimes the only chunk) on the scanning chunk server. The mounts were affected somehow (hard not too), you could see visible pauses every few seconds, but you couldn't say all I/O was completely blocked during the scanning process. It was just slower and had "hiccups".
What I'm trying to say here is, it's suspicious how strongly your system was affected during scanning and how much it blocked the rest of the system. It should not happen, from the architectural point of view and it did not happen it our tests. There has to be another factor here, but I cannot guess what it is, if it's not hardware related.

And another side note. This is not in any way a dig at @onlyjob, more of a warning to anybody that might stumble upon this thread: moving disks between chunk servers is not an operation one should undertake often and treat lightly. First, a scanning process that finds duplicate chunks will always slow down, because, for the sake of the system integrity, chunk server needs to read more information from the local file system about duplicate chunks than about non-duplicate chunks. This cannot be avoided. Second, all the duplicate chunks will occupy space on your system for a time (currently 7 days, to be configurable in the future), and after that time is up, they need to be deleted. This operation basically gives your system more stuff to do. So the only scenario (and the actual reason this operation is supported at all) in which one puts a disk with chunks from one chunk server to another should be when there was a hardware problem with one of the chunk servers and there is no replacement hardware, and the disk contains chunks that are not available anywhere else. If this is not the case (there are undergoal, but not missing chunks in the system) - let the system rebuild itself and if you want to re-use a hdd, clean format it and then put it in one of the chunk servers.

Guess what I wrote here will make it to our best practices page too :)

**Comment by onlyjob** [comment]
Thank for trying to replicate the problem, @chogata. I have little to add. Two archival chunkservers have around 30 million chunks each (two replicas). Number of duplicate files is around 6 million on one chunkserver and 12 million on another. I suspect that profound slowdown in scanning may be related to number of duplicate chunks -- perhaps too many to walk the list (array) efficiently.

Some archival chunks spilled into other chunkservers and still slowly migrating back. Maybe I've re-configured a storage class some time ago or (more likely) it could be #249, @298, #237 -- the worst MooseFS bugs as far as I'm concerned, far more severe than this one...
That may be a hint regarding blocking I/O.

As for "wrong header", it is probably a replication (or rebalance) bug in presence of duplicate chunks. I'm guessing chunkserver is trying to write (move) a chunk between local HDDs or replicate from another chunkserver when chunks already exist among duplicates.  
Archival data on affected chunkservers is "write once", never to be modified or accessed by application...

**Comment by onlyjob** [comment]
Slow scanning is reproducible and definitely related to duplicate chunks. On chunkserver with 30 million chunks adding another HDD mostly with duplicates scans extremely slow. Because chunkserver only counts non-duplicate chunks I see very slow increase in number of chunks in CGI/Disks view for that particular HDD. After 30 minutes of scanning there are only 35 chunks there and scanning did not complete even 1% yet. HDD have over 10 million chunks and it is added to `mfshdd.cfg` as follows: `</mnt/bay3/ext4`.

**Comment by chogata** [comment]
That's what I wrote - scanning with duplicate chunks **_will be slower_**. Always. And it cannot be avoided. Duplicate chunks are not a natural state of MooseFS and are only caused by swapping disks between servers - see my previous post.

In your particular case there might be one more problem - your system was affected by the bug in the counter distributing chunks into directories, resulting in a very unbalanced distribution of chunks (a lot in one directory and the others mostly empty). This will slow down the duplicate chunk scanning even more, as operations on "long" directories are slower in every regular hdd file system.

**Comment by onlyjob** [comment]
Yes but how much slower? 3% of scanning completed in 23 hours.

While HDD was disconnected I spread chunks from overloaded directories so that is not the major factor in slow scanning.

**Comment by onlyjob** [comment]
If all the reported problems were not enough, here is another one:  
an hour 168 has come and finally chunkserver started to remove duplicated chunks.
_It went offline without activating maintenance mode_ so now all other chunkservers frantically replicate "endangered" chunks. At first I've thought that the chunkserver is crashed but no, it is still running, using some CPU cycles and apparently removing files as the free space slowly increases while number of allocated inodes decline.

For MooseFS however chunkserver appears as if it is offline and that's undesirable.

**Comment by onlyjob** [comment]
About 5 hours later chunkserver re-connected with master:

    long loop detected (14977.132197s)

**Comment by chogata** [comment]
The last is an issue and it will be fixed. The problem was your chunk server tried to delete all those duplicates in one loop. As I wrote before, inserting a "foreign" disk to a chunk server was supposed to be an emergency only situation and we never assumed there will be 5 millions or more duplicates to delete. We will change the algorithm so they would be deleted in batches.

The 3% in 23 hours - I cannot explain that, it never happened to us. There must be some additional factor, but I'm afraid without a direct access to an affected system we cannot even try to guess what that might be.

**Comment by onlyjob** [comment]
> The 3% in 23 hours - I cannot explain that, it never happened to us. There must be some additional factor,

I already mentioned this factor here. The problem is not specific to our systems and I've seen in on two very different chunksevers. 

Originally there were some undergoal chunks and because HDD was scanning too slow I left it out and let replication to do the work. A week later when there were no undergoal chunks left, I've re-connected HDD and noticed that scanning became much slower. As a matter of fact it is still scanning since 3 days ago (currently 18%) and while there were some undergoal chunks it could reach 40% in some hours. Now all chunks on that HDD are duplicates and large volume of duplicate chunks make scanning incredibly slow.

_Scanning slowdown is proportional to number of duplicate chunks. To reproduce take an HDD with 20 million chunk files, clone it and add cloned HDD to the chunkserver._

**Comment by onlyjob** [comment]
And more troubles: remember that HDD with 5 million duplicates, which were waiting to be deleted for a week then being deleted for hours while chunkserver was offline? Just now that HDD was marked as "damaged" due to burst of errors like the following:

    hdd_io_begin: file:/mnt/03/ext4//68/chunk_00000000056AF850_00000001.mfs - open error: ENOENT (No such file or directory)

Of course no hardware errors were logged and there are no structural file system errors either (fsck). `.chunksdb` file was suspiciously small when I commented disk out in `mfshdd.cfg` so I've deleted it before re-connecting HDD back to the chunkserver...

To me it looks like duplicates handling is clashing with internal rebalancing between local disks.

**Comment by acid-maker** [comment]
You are right !!!

The condition in internal rebalance is wrong - fixing

**Comment by onlyjob** [comment]
Thanks for all the corrections and fixes in 3.0.110.
Some things are definitely better but one thing is not (and perhaps a little worse) -- scanning of HDD full of duplicate chunks.

Prior to 110 it was just slow but now chunkserver logs `long loop detected` repeatedly during scanning while falling off the cluster, re-connecting and so on causing disruptions and timeouts in CGI/Disks view:

```
Traceback (most recent call last):
  File "/usr/share/moosefs-cgi/mfs.cgi", line 1461, in command
    header = self.myrecv(8)
  File "/usr/share/moosefs-cgi/mfs.cgi", line 1445, in myrecv
    chunk = self.socket.recv(leng-len(msg))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/moosefs-cgi/mfs.cgi", line 4563, in 
    data,length = conn.command(CLTOCS_HDD_LIST,CSTOCL_HDD_LIST)
  File "/usr/share/moosefs-cgi/mfs.cgi", line 1474, in command
    raise RuntimeError("MFS communication error")
RuntimeError: MFS communication error
```

Currently chunkserver holds around 30 million chunks on 6 HDDs and scanning 7th HDD with about 20 million chunks (approximately) most of which are duplicates at the speed of roughly 1% per hour (or slower).  
The reason why I'm trying to add this HDD is that most certainly it have few chunks that are "missing" and scanning it is crucial to recover unreadable files.

**Comment by onlyjob** [comment]
Also I strongly suspect that duplicate chunks postponed for removal are not used in case when all active chunks are lost due to CRC check or "bad header" errors. It would be great to recover valid chunks automatically in such cases. In other words, "missing" chunks can still be available among duplicate chunks scheduled for deletion.

**Comment by chogata** [comment]
Still can't replicate. 20 million duplicates on a mechanical HDD scans for around 200 sec in here and whatever we do, we can't get it to be slower...

If you still need to recover some missing chunks, it might be better to connect the disk that has them to another chunk server rather than forcing the system to deal with duplicates. If you don't have a separate machine, run a second chunk server process on one of your regular chunk server machines. Just make a second config, use different values for `DATA_PATH`, `HDD_CONF_FILENAME`, `CSSERV_LISTEN_PORT` and `SYSLOG_IDENT` variables, put this one disk in the new chunk server's hdd config as marked for removal before you even start it, and run it.

You won't have duplicates, so if there isn't another problem with scanning in your system - scanning should be fast. The disk will be marked for removal, so MooseFS will not try to use it for storage. And if it finds any missing chunks on it, it will happily replicate them to somewhere else.

**Comment by onlyjob** [comment]
In regards to slow scanning, long loops and chunkserver's high CPU utilisation, it is definitely due to number of chunks per chunkserver: I've created a new chunkserver on the same machine and moved slow HDD to the new chunkserver (leaving 5 other HDDs on the original chunkserver that was struggling) -- now two chunkservers perform much more adequately together comparing to one when it was handling all HDDs, including speed of scanning. All that on the same machine with no changes to hardware or other configuration.  

It should not be necessary to breed chunkservers as workaround for their poor performance...

**Comment by onlyjob** [comment]
Duplicates handling is still somewhat flawed. On chunkserver with only SSD disks and about a million chunks, presence of 30_000 duplicates throws frequent "long loop detected" and "replicator: connection lost" errors under regular load -- a problem never to be seen on the very chunkserver without duplicate chunks. CGI/Disks view is often timeouts when duplicate chunks are present...
